name: Testplugin
version: ${project.version}
main: de.polygondev.testplugin.Testplugin
api-version: 1.13
depend: [
    Inventoryapi
]
commands:
  invopen:
    description: ja so und nu?
    usage: läuft