name: InventoryApi
version: 1.1.6
main: de.polygondev.inventoryapi.InventoryApi
api-version: 1.13
authors: [ChiAkuma, WhatzGames]
description: Minecraft Inventory-Gui API an easier implementation of GUI elements inside a players Inventory
